In [ ]:
import numpy as np

In [ ]:
# Q1.Create a 1D NumPy array with numbers from 1 to 10.
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Q2.Create a 3×3 matrix with all zeros.
import numpy as np
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Q3.Create a 4×4 identity matrix.
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Q4.Print the 3rd element of an array.
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [ ]:
# Q5. Print the last element of an array.
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[-1])

5


In [ ]:
# Q6.Print elements from index 2 to 5.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]


In [ ]:
# Q7.Print alternate elements.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::2])

[1 3 5 7 9]


In [ ]:
# Q8.Create a 4×4 matrix: x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) 8.1 Print the 2nd row. 8.2 Print the 3rd column. 8.3 Print the submatrix: [[6,7], [10,11]]
import numpy as np
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
print(x)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#8-1. print 2nd row.
import numpy as np
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
print(x[1])


[5 6 7 8]


In [ ]:
# 8-2. Print the 3rd column.
import numpy as np
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
print(x[0:,2])

[ 3  7 11 15]


In [ ]:
# Q9.Create an array from 1 to 12 and reshape it into: 9.1 3×4 matrix 9.2 2×6 matrix
import numpy as np
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 9-1.3*4 matrix.
# how to convert 3*4 matrix by the numbers 1 to 12.
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 9-2. 2*6 matrix.
import numpy as np
arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Q10.Flatten any 3*3 matrix into a 1D array
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]
